// Pure renderers: SchemaSnapshot → Mermaid (ER + graph-of-labels) and the
// SCHEMA.md scaffold. No I/O, no driver imports — unit-tested with canned input.
//
// Determinism: the snapshot is already fully sorted, so these renderers are a
// straight, order-preserving projection. Cardinality is a constant (never
// data-derived) per ADR 0004.

import type { SchemaSnapshot } from './snapshot.js';

const BANNER = '%% Auto-generated by scripts/schema-diagram/generate.ts — do not edit by hand.';

/** Mermaid entity/node ids must be alphanumeric/underscore. Labels are, but a
 *  multi-label key ("Artist&Musician") would not be — sanitize defensively. */
function mermaidId(label: string): string {
  return label.replace(/[^A-Za-z0-9_]/g, '_');
}

/** Collapse a (sorted) type list into a single Mermaid-safe attribute token. */
function typeToken(types: string[]): string {
  const joined = types.join('|').replace(/[^A-Za-z0-9_]/g, '_');
  return joined.length > 0 ? joined : 'Any';
}

export function renderErDiagram(snapshot: SchemaSnapshot): string {
  const lines: string[] = [BANNER, 'erDiagram'];

  for (const { label, properties } of snapshot.labels) {
    lines.push(`    ${mermaidId(label)} {`);
    for (const p of properties) {
      const key = p.unique ? ' PK' : '';
      const flags: string[] = [];
      if (p.indexed && !p.unique) flags.push('indexed');
      if (p.mandatory) flags.push('required');
      const comment = flags.length > 0 ? ` "${flags.join(', ')}"` : '';
      lines.push(`        ${typeToken(p.types)} ${p.name}${key}${comment}`);
    }
    lines.push('    }');
  }

  for (const r of snapshot.relationships) {
    lines.push(`    ${mermaidId(r.from)} }o--o{ ${mermaidId(r.to)} : "${r.type}"`);
  }

  return lines.join('\n');
}

export function renderGraphDiagram(snapshot: SchemaSnapshot): string {
  const lines: string[] = [BANNER, 'flowchart LR'];

  for (const { label } of snapshot.labels) {
    lines.push(`    ${mermaidId(label)}["${label}"]`);
  }
  for (const r of snapshot.relationships) {
    lines.push(`    ${mermaidId(r.from)} -->|"${r.type}"| ${mermaidId(r.to)}`);
  }

  return lines.join('\n');
}

/** Replace the body between `<!-- schema:<name>:start -->` / `:end` markers with
 *  a fenced mermaid block. Pure (string in, string out) — mirrors the
 *  scripts/diagrams inliner but in the `schema:` namespace. */
export function inlineIntoMarkdown(name: string, body: string, markdown: string): string {
  const startMarker = `<!-- schema:${name}:start -->`;
  const endMarker = `<!-- schema:${name}:end -->`;
  const startIdx = markdown.indexOf(startMarker);
  const endIdx = markdown.indexOf(endMarker);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`SCHEMA.md is missing the marker pair for "${name}"`);
  }
  const fenced = `${startMarker}\n\n\`\`\`mermaid\n${body}\n\`\`\`\n\n${endMarker}`;
  return markdown.slice(0, startIdx) + fenced + markdown.slice(endIdx + endMarker.length);
}

const SCHEMA_MD_SCAFFOLD = `<!-- Auto-generated by \`pnpm schema:diagram\` from a live Neo4j introspection. Do not edit by hand. -->

# Data-model schema

> ⚠️ Generated by introspecting the live graph (ADR 0004). Until the schema-diagram
> workflow is wired up, this is a **manual point-in-time capture** — re-run
> \`pnpm schema:diagram\` to refresh. Node/relationship names and properties below
> are the authoritative model; the tables in the service handbook point here.

## Entity-relationship diagram

Each node label, its properties (\`PK\` = unique key), and the relationships
between them.

<!-- schema:er:start -->
<!-- schema:er:end -->

## Graph overview

Labels as nodes, relationship types as edges — the at-a-glance shape of the graph.

<!-- schema:graph:start -->
<!-- schema:graph:end -->
`;

export function buildSchemaMarkdown(erBody: string, graphBody: string): string {
  let md = SCHEMA_MD_SCAFFOLD;
  md = inlineIntoMarkdown('er', erBody, md);
  md = inlineIntoMarkdown('graph', graphBody, md);
  return md;
}
