#!/usr/bin/env tsx
// Regenerate architecture diagrams under infra/diagrams/.
//
// Outputs:
//   resource-graph.svg    — Inframap --raw view (every resource + dependency)
//   per-file/<name>.mmd   — one Mermaid diagram per .tf file
//   request-flow.mmd      — hand-maintained, source of truth, inlined into
//                           markdown files between marker comments.
//
// Inframap's default "curated" view embeds AWS icons from a local cache via
// absolute file paths, which won't render outside the author's machine. We
// use --raw so the SVG is self-contained and portable.
//
// Markdown inlining: for each (mmdName, [files]) entry in MARKDOWN_TARGETS we
// look for the marker pair:
//   <!-- diagrams:<mmdName>:start -->
//   <!-- diagrams:<mmdName>:end -->
// in each file and replace the content between them with a ```mermaid fence
// containing request-flow.mmd. This keeps README + RUNBOOK in sync from one
// source.
//
// Requires `inframap` and `dot` on PATH. README documents install.

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const REPO_ROOT = resolve(import.meta.dirname, '..', '..');
const TF_DIR = join(REPO_ROOT, 'infra', 'terraform');
const OUT_DIR = join(REPO_ROOT, 'infra', 'diagrams');
const PER_FILE_DIR = join(OUT_DIR, 'per-file');

type ResourceRef = {
  kind: 'resource' | 'data';
  type: string;
  name: string;
  file: string;
};

type Address = string; // e.g. "aws_vpc.main" or "data.aws_ami.al2023"

const SKIP_FILES = new Set(['outputs.tf', 'variables.tf']);

// Which markdown files should have which .mmd inlined into them.
const MARKDOWN_TARGETS: Record<string, string[]> = {
  'request-flow': ['README.md', 'infra/RUNBOOK.md'],
};

function listTfFiles(): string[] {
  return readdirSync(TF_DIR)
    .filter((f) => f.endsWith('.tf') && !SKIP_FILES.has(f))
    .sort();
}

// Strip line and block comments so they can't produce false-positive matches.
function stripComments(src: string): string {
  return src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])(\/\/|#)[^\n]*/g, '$1');
}

const DECL_RE = /^(resource|data)\s+"([a-zA-Z0-9_-]+)"\s+"([a-zA-Z0-9_-]+)"\s*\{/gm;

function parseDeclarations(src: string, file: string): ResourceRef[] {
  const out: ResourceRef[] = [];
  for (const m of src.matchAll(DECL_RE)) {
    out.push({
      kind: m[1] as 'resource' | 'data',
      type: m[2],
      name: m[3],
      file,
    });
  }
  return out;
}

function addressOf(r: ResourceRef): Address {
  return r.kind === 'data' ? `data.${r.type}.${r.name}` : `${r.type}.${r.name}`;
}

// Find which declared addresses are referenced in `src`. We look for token
// patterns and intersect with the known set so we never invent references.
function findReferences(src: string, known: Set<Address>): Set<Address> {
  const found = new Set<Address>();
  // Resource refs: aws_foo.bar(.attr)?
  const RES_RE = /\b([a-z][a-z0-9_]+)\.([a-z][a-z0-9_]+)/g;
  for (const m of src.matchAll(RES_RE)) {
    const addr = `${m[1]}.${m[2]}`;
    if (known.has(addr)) found.add(addr);
  }
  // Data refs: data.aws_foo.bar
  const DATA_RE = /\bdata\.([a-z][a-z0-9_]+)\.([a-z][a-z0-9_]+)/g;
  for (const m of src.matchAll(DATA_RE)) {
    const addr = `data.${m[1]}.${m[2]}`;
    if (known.has(addr)) found.add(addr);
  }
  return found;
}

function mermaidId(addr: Address): string {
  return addr.replace(/[^a-zA-Z0-9]/g, '_');
}

function shortType(type: string): string {
  // aws_cloudwatch_metric_alarm -> CW metric alarm
  return type.replace(/^aws_/, '').replace(/_/g, ' ');
}

function buildPerFileMermaid(
  file: string,
  declsInFile: ResourceRef[],
  refsFromFile: Set<Address>,
  declToFile: Map<Address, string>,
): string {
  const lines: string[] = [];
  lines.push('%% Auto-generated by scripts/diagrams/generate.ts — do not edit by hand.');
  lines.push(`%% Source: infra/terraform/${file}`);
  lines.push('flowchart LR');

  const declAddrs = new Set(declsInFile.map(addressOf));
  const externalRefs = [...refsFromFile].filter((a) => !declAddrs.has(a));

  // Subgraph: resources declared in this file.
  lines.push(`  subgraph this["${file}"]`);
  for (const d of declsInFile) {
    const addr = addressOf(d);
    const label = `${d.kind === 'data' ? '📥 ' : ''}${d.name}<br/><small>${shortType(d.type)}</small>`;
    lines.push(`    ${mermaidId(addr)}["${label}"]`);
  }
  lines.push('  end');

  // External resources, grouped by source file.
  const byFile = new Map<string, Address[]>();
  for (const addr of externalRefs) {
    const f = declToFile.get(addr) ?? 'unknown';
    if (!byFile.has(f)) byFile.set(f, []);
    byFile.get(f)!.push(addr);
  }

  for (const [otherFile, addrs] of [...byFile.entries()].sort()) {
    const sgId = `ext_${mermaidId(otherFile)}`;
    lines.push(`  subgraph ${sgId}["${otherFile}"]`);
    for (const addr of addrs) {
      const last = addr.split('.').slice(-2).join('.');
      lines.push(`    ${mermaidId(addr)}(["${last}"])`);
    }
    lines.push('  end');
  }

  // Edges: every declared resource in this file -> every external ref it might
  // touch. We don't know exact attribute usage at this granularity, so we draw
  // a single edge from the file's "this" subgraph border into each external
  // node. Render with a hub node to keep edge count manageable.
  if (externalRefs.length > 0 && declsInFile.length > 0) {
    // Use the first declared resource as hub for visual anchor.
    for (const addr of externalRefs) {
      lines.push(`  this -.-> ${mermaidId(addr)}`);
    }
  }

  return lines.join('\n') + '\n';
}

function run(cmd: string, args: string[], opts: { input?: string } = {}): Buffer {
  const r = spawnSync(cmd, args, {
    input: opts.input,
    cwd: REPO_ROOT,
  });
  if (r.status !== 0) {
    throw new Error(
      `${cmd} ${args.join(' ')} failed (exit ${r.status}):\n${r.stderr?.toString() ?? ''}`,
    );
  }
  return r.stdout;
}

function ensureToolsAvailable(): void {
  for (const tool of ['inframap', 'dot']) {
    const r = spawnSync('which', [tool]);
    if (r.status !== 0) {
      console.error(
        `\n❌ "${tool}" not found on PATH.\n` +
          `   macOS:  brew install inframap graphviz\n` +
          `   Linux:  see README "Architecture diagrams" section\n`,
      );
      process.exit(1);
    }
  }
}

// Read a .mmd file and strip the leading %% header-comment block (the
// "this file is the source of truth" preamble). Inlined output should be
// just the diagram itself.
function loadMermaidBody(mmdPath: string): string {
  const raw = readFileSync(mmdPath, 'utf8');
  const lines = raw.split('\n');
  // Drop leading %% comment lines (and any blank lines between them).
  let i = 0;
  while (i < lines.length && (lines[i].startsWith('%%') || lines[i].trim() === '')) {
    i++;
  }
  return lines.slice(i).join('\n').trimEnd();
}

function inlineIntoMarkdown(mmdName: string, body: string, targets: string[]): void {
  const startMarker = `<!-- diagrams:${mmdName}:start -->`;
  const endMarker = `<!-- diagrams:${mmdName}:end -->`;
  const fenced = `${startMarker}\n\n\`\`\`mermaid\n${body}\n\`\`\`\n\n${endMarker}`;

  for (const rel of targets) {
    const path = join(REPO_ROOT, rel);
    if (!existsSync(path)) {
      console.warn(`  ⚠️  ${rel} not found — skipping inline`);
      continue;
    }
    const src = readFileSync(path, 'utf8');
    const startIdx = src.indexOf(startMarker);
    const endIdx = src.indexOf(endMarker);
    if (startIdx === -1 || endIdx === -1) {
      console.warn(`  ⚠️  ${rel} is missing marker pair for "${mmdName}" — skipping inline`);
      continue;
    }
    const updated = src.slice(0, startIdx) + fenced + src.slice(endIdx + endMarker.length);
    if (updated === src) {
      console.log(`  ${rel} already up to date`);
    } else {
      writeFileSync(path, updated);
      console.log(`  inlined ${mmdName} into ${rel}`);
    }
  }
}

function renderResourceGraph(outFile: string): void {
  const dot = run('inframap', ['generate', '--hcl', '--raw', TF_DIR]).toString();
  const svg = run('dot', ['-Tsvg'], { input: dot });
  writeFileSync(outFile, svg);
  console.log(`  wrote ${outFile.replace(REPO_ROOT + '/', '')}`);
}

function main(): void {
  ensureToolsAvailable();

  if (existsSync(PER_FILE_DIR)) {
    rmSync(PER_FILE_DIR, { recursive: true });
  }
  mkdirSync(PER_FILE_DIR, { recursive: true });

  const files = listTfFiles();
  const allDecls: ResourceRef[] = [];
  const fileSources = new Map<string, string>();

  for (const file of files) {
    const src = stripComments(readFileSync(join(TF_DIR, file), 'utf8'));
    fileSources.set(file, src);
    allDecls.push(...parseDeclarations(src, file));
  }

  const declToFile = new Map<Address, string>();
  for (const d of allDecls) declToFile.set(addressOf(d), d.file);
  const knownAddrs = new Set(declToFile.keys());

  console.log(`Parsed ${allDecls.length} resources across ${files.length} files.`);

  for (const file of files) {
    const declsInFile = allDecls.filter((d) => d.file === file);
    if (declsInFile.length === 0) continue;
    const refs = findReferences(fileSources.get(file)!, knownAddrs);
    const mmd = buildPerFileMermaid(file, declsInFile, refs, declToFile);
    const out = join(PER_FILE_DIR, file.replace(/\.tf$/, '.mmd'));
    writeFileSync(out, mmd);
    console.log(`  wrote ${out.replace(REPO_ROOT + '/', '')}`);
  }

  console.log('\nRendering resource graph...');
  renderResourceGraph(join(OUT_DIR, 'resource-graph.svg'));

  console.log('\nInlining Mermaid sources into markdown...');
  for (const [mmdName, targets] of Object.entries(MARKDOWN_TARGETS)) {
    const mmdPath = join(OUT_DIR, `${mmdName}.mmd`);
    if (!existsSync(mmdPath)) {
      console.warn(`  ⚠️  ${mmdPath} missing — skipping`);
      continue;
    }
    inlineIntoMarkdown(mmdName, loadMermaidBody(mmdPath), targets);
  }

  console.log('\n✅ Diagrams regenerated.');
}

main();
